### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ballerarge** [adzach/AscensionGame#2]
### RJ and Zach
- [ ] Creating new levels
- [x] Initializing hero position
- [ ] Smoothing out certain collisions
- [ ] Center camera on hero
---
### Ben and Chad
- [ ] Enemies take damage
- [ ] Enemies spawning in locations on levels
---
### Michael and Charlie
- [ ] Hero animations and sprites
- [ ] Hero attacking
- [ ] Lighting stuff?

**Comment by adzach** [comment]
@michaelnutt24 @ballerarge @charliehershberger @katzb123 @estillcn Make sure to check off things as you do them! :pizza: :pizza:
